spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux_vue3?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret
